---
title: "Untitled"
author: "Michelle K Jamieson"
date: "2022-09-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load packages 

```{r package load}
if (!require(pacman)) {
  install.packages("pacman")
  library(pacman)
}
p_load(
  collapse,
  effectsize,# C/C++ based package for advanced data transformation and statistical computing
  consort, # automatic consort diags
  DataExplorer, # automated data exploration process for analytic tasks and predictive modeling
  dataReporter, # generates a custom data report with a thorough summary of the checks
  ggpubr, # creating publication ready plots
  patchwork,
  gtsummary, # publication-ready analytical and summary tables
  haven, # read and write various data formats used by other statistical packages
  glue,
  here, # constructs paths to project's files
  janitor, # examines and cleans dirty data
  psych, # general purpose toolbox for personality, psychometric theory
  questionr, # make the processing and analysis of surveys easier
  readxl, # read in excel files
  report, # produces reports of models and data frames according to best practices
  skimr, # simple to use summary function that can be used with pipes
  styler, # pretty-prints R code without changing the user's formatting intent
  summarytools, # data frame summaries
  tidyverse, # opinionated collection of R packages designed for data science
  excel.link,
  kableExtra,
  rstatix
)

# check packages
pacman::p_loaded()

# check wd
here()
```

# Read in Data 
``` {r read in data}
# read in
# read file with pass
headsup_t0_t1_t2_t3 <- xl.read.file("HeadsUpStage3_DATA_All_Batches_T0_T1_T2_T3_Oct.xlsx", password = "HuPs3@OctC1C2T0123")
```

# Skim
```{r skim}
skimr::skim(headsup_t0_t1_t2_t3)
```


# Tidy 
```{r tidy}
# living arrangements 
headsup_t0_t1_t2_t3$living_arrangements <- recode_factor(headsup_t0_t1_t2_t3$living_arrangements,
"Alone" = "Alone",
"Alone (supported living)"  = "Alone",
"Living in group accommodation" = "Alone",
"Living with family" = "Living with family",
"Living with spouse/partner" = "Living with spouse/partner"
)
headsup_t0_t1_t2_t3 %>%
  tabyl(living_arrangements)

# ethnicity 
headsup_t0_t1_t2_t3$ethnicity <- recode_factor(headsup_t0_t1_t2_t3$ethnicity,
"White British" = "White",
"Other Italian" = "White",
"White Irish" = "White",
"White Canadian" = "White",
"White English (Other British)" = "White",
"White Other British" = "White",
"White Scottish" = "White",
"Caribbean British" = "Other",
"Chinese" = "Other",
"African Caribbean" = "Other",
"Mixed UK British" = "Other"
)
headsup_t0_t1_t2_t3 %>%
  tabyl(ethnicity) %>%
  adorn_totals()
headsup_t0_t1_t2_t3$ethnicity <- recode_factor(headsup_t0_t1_t2_t3$ethnicity,
"White" = "White",
"Other" = "Other",
" African Caribbean" = "Other"
)
headsup_t0_t1_t2_t3 %>%
  tabyl(ethnicity) %>%
  adorn_totals()

# employment
headsup_t0_t1_t2_t3 %>%
  tabyl(employ_status) %>%
  adorn_totals()
headsup_t0_t1_t2_t3$employ_status <- recode_factor(headsup_t0_t1_t2_t3$employ_status,
"full-time employment" = "Economically active",
"Full-time employment " = "Economically active",
"Full-time employment" = "Economically active",
"Full-time employment (phased return)" = "Economically active",
"Part-time employed" = "Economically active",
"Part-time employment " = "Economically active",
"Part-time employment" = "Economically active",
"Part-time self employed" = "Economically active",
"Self-employed - phased return to work" = "Economically active",
"Self-employed but not working since stroke" = "Economically active",
"Homemaker" = "Economically inactive",
"Long-term sick" = "Economically inactive",
"Long-term sick/ phased return" = "Economically inactive",
"Long term sick" = "Economically inactive",
"Retired" = "Economically inactive",
"retired (ill health)" = "Economically inactive",
"Short-term sick" = "Economically inactive",
"Unemployed" = "Economically inactive",
"Unemployed " = "Economically inactive",
"Unemployed due to stroke" = "Economically inactive",
)

headsup_t0_t1_t2_t3 %>%
  tabyl(employ_status) %>%
  adorn_totals()  

# education 
headsup_t0_t1_t2_t3 %>%
  count(edu_status)
headsup_t0_t1_t2_t3$edu_status <- recode_factor(headsup_t0_t1_t2_t3$edu_status,
"Completed secondary school" = "Secondary school",
"Completed Secondary School" = "Secondary school",
" Completed secondary school (O-levels, GCSE, Highers) " = "Secondary school",
"Some secondary school" ="Secondary school",
"College/foundation course" = "College",
"College/foundation/further education" = "College",
"Doctorate" = "University",
"Master's degree" = "University",
"Master's Degree" = "University",
"Undergraduate degree" = "University",
"Undergraduate Degree" = "University",
"Undergraduate degree in social work" = "University"
)
headsup_t0_t1_t2_t3 %>%
  tabyl(edu_status) %>%
  adorn_totals()  

# fatigue
headsup_t0_t1_t2_t3 %>%
  tabyl(fatigue) %>%
  adorn_totals()
headsup_t0_t1_t2_t3 %>%
  mutate(fatigue = case_when(
        fatigue == "yes" |
        fatigue == "Yes"
        ~ "Yes",
        fatigue == "No"
        ~ "No"
    )) %>%
  structure(label = "Fatigue") -> headsup_t0_t1_t2_t3
headsup_t0_t1_t2_t3 %>%
  tabyl(fatigue) %>%
  adorn_totals()

# recruitment source 
headsup_t0_t1_t2_t3$recruitment_source <- recode_factor(headsup_t0_t1_t2_t3$recruitment_source,
"Ann Doyle (TSA)" = "TSA",
"Colleague at work emailed the TSA Staff/Stroke survivors group " = "TSA",
"Email from the Stroke Association" = "TSA",
"Information passed on by Becca Reilly at TSA" = "TSA",
"Jane Hammon, Stroke Association corodinator" = "TSA",
"Local TSA Group" = "TSA",
"OT and community psychologist and befriender (stroke Association) " = "TSA",
"Stroke Group Leader (local community)" = "TSA",
"Stroke support coordinator TSA emailed HU details" = "TSA",
"Through known contacts at TSA" = "TSA",
"TSA" = "TSA",
"TSA  Back to Work Stroke Group" = "TSA",
"TSA (Nick Clarke)" = "TSA",
"TSA contact" = "TSA",
"TSA coordinator emailed info" = "TSA",
"TSA coordinator Mandy Back to Work group" = "TSA",
"TSA facilitator, also Rosetta Life" = "TSA",
"TSA Link worker" = "TSA",
"TSA Stroke Group (BD met with group)" = "TSA",
"TSA support aphasia group in Oxford" = "TSA",
"Katie McPherson, Specialist Neurophysio, Edinburgh NOT NHS" = "NHS",
"Young Stroke Survivors South (Mark Cadman)" = "NHS",
"Leonard Cheshire centre in Stockport forwarded HU info" = "NHS",
"Neighbour (physio) told her about HU" = "NHS",
"Stroke nurse gave him a flier" = "NHS",
"Physio, Jude, in Elgan" = "NHS",
"Speech Therapist" = "NHS",
"Stroke Survivor UK Facebook group post" = "Social media",
"Stroke Assoc FB page" = "Social media",
"Facebook. Stroke Recovery UK" = "Social media",
"Stroke Recovery UK (Facebook)" = "Social media",
"Stroke Recovery UK Facebook page" = "Social media",
"Previous interest in HU F2 but didn't participate" = "Social media",
"TSA Facebook (M. Hunter)" = "Social media",
"Looked online (Google) for support/stroke nurse also gave more recent info" = "Social media",
"Pathways Tweet (forwarded by a friend)" = "Social media",
"Facebook, Stroke Recovery UK" = "Social media",
"Facebook, Different Strokes" = "Social media",
"Facebook stroke site (couldn't recall which)" = "Social media",
"Facebook page" = "Social media",
"BD's Facebook post" = "Social media",
"Can't remember, may have been Facebook or TSA" = "Social media",
"TSA Twitter" = "Social media",
"TSA various routes" = "Social media",
"TSA website" = "Social media",
"Twitter - follows stroke related tweets" = "Social media",
"Twitter - Maggie" = "Social media",
"Twitter (Maggie's post)" = "Social media",
"Twitter (TSA tweet)" = "Social media",
"Twitter posts and Different Strokes FB post" = "Social media",
"via daughter Pauline" = "Social media"
)
headsup_t0_t1_t2_t3 %>%
  tabyl(recruitment_source) %>%
  adorn_totals()


```

# Group A and B Split
```{r grp split}
headsup_group_a <- headsup_t0_t1_t2_t3 [headsup_t0_t1_t2_t3$group == "A", ] 

headsup_group_b <- headsup_t0_t1_t2_t3 [headsup_t0_t1_t2_t3$group == "B", ]

```

# Demographics
```{r demog grps a b}
# Age, Gender, Time Post-Stroke, Living arrangements, Ethnicity, Employment status, Highest educational attainment, Fatigue, Dyad status, Montreal Cognitive assessment – Blind (MoCA-B), Recruitment source 
mean(headsup_group_a$age)
mean(headsup_group_b$age)
IQR(headsup_group_b$time_since_stroke_mths)
median(headsup_group_b$time_since_stroke_mths)
# grp a
headsup_group_a %>%
  tabyl(gender) %>%
  adorn_pct_formatting()
headsup_group_a %>%
  tabyl(time_since_stroke_mths)  %>%
  adorn_pct_formatting()
headsup_group_a %>%
  tabyl(living_arrangements) %>%
  adorn_pct_formatting()
headsup_t0_t1_t2_t3 %>%
  tabyl(ethnicity)

headsup_t0_t1_t2_t3 %>%
  tabyl(ethnicity)
headsup_group_a %>%
  tabyl(ethnicity) %>%
  adorn_pct_formatting()
headsup_group_a %>%
  tabyl(employ_status) %>%
  adorn_pct_formatting()
headsup_group_a %>%
  tabyl(edu_status) %>%
  adorn_pct_formatting()
headsup_group_a %>%
  tabyl(fatigue) %>%
  adorn_pct_formatting()
headsup_group_a %>%
  tabyl(dyad_status) %>%
  adorn_pct_formatting()
headsup_group_a %>%
  tabyl(recruitment_source) %>%
  adorn_pct_formatting()

# grp b
headsup_group_b %>%
  get_summary_stats(age)
headsup_group_b %>%
  tabyl(gender) %>%
  adorn_pct_formatting()
headsup_group_b %>%
  get_summary_stats(time_since_stroke_mths) 
headsup_group_b %>%
  tabyl(living_arrangements) %>%
  adorn_pct_formatting()
headsup_group_b %>%
  tabyl(ethnicity) %>%
  adorn_pct_formatting()
headsup_group_b %>%
  tabyl(employ_status) %>%
  adorn_pct_formatting()
headsup_group_b %>%
  tabyl(edu_status) %>%
  adorn_pct_formatting()
headsup_group_b %>%
  tabyl(fatigue) %>%
  adorn_pct_formatting()
headsup_group_b %>%
  tabyl(dyad_status) %>%
  adorn_pct_formatting()
headsup_group_b %>%
  tabyl(recruitment_source) %>%
  adorn_pct_formatting()

```

# Short Form Stroke Impact Scale Keys
```{r sf sis keys}
# # Short Form Stroke Impact Scale 
# sf_sis_a.keys <- list(
#   q1_t0 = c(
#     "sf_sis_1_T0"
#   ),
#   q2_t0 = c(
#     "sf_sis_2_T0"
#   ),
#   q3_t0 = c(
#     "sf_sis_3_T0"
#   ),
#   q4_t0 = c(
#     "sf_sis_4_T0"
#   ),
#   q5_t0 = c(
#     "sf_sis_5_T0"
#   ),
#   q6_t0 = c(
#     "sf_sis_6_T0"
#   ),
#   q7_t0 = c(
#     "sf_sis_7_T0"
#   ),
#   q8_t0 = c(
#     "sf_sis_8_T0"
#   ), 
#   sf_sis_total_t0 = c(
#     "sf_sis_1_T0",
#     "sf_sis_2_T0",
#     "sf_sis_3_T0",
#     "sf_sis_4_T0",
#     "sf_sis_5_T0",
#     "sf_sis_6_T0",
#     "sf_sis_7_T0",
#     "sf_sis_8_T0"
#   ),
#   q1_t1 = c(
#     "sf_sis_1_T1"
#   ),
#   q2_t1 = c(
#     "sf_sis_2_T1"
#   ),
#   q3_t1 = c(
#     "sf_sis_3_T1"
#   ),
#   q4_t1 = c(
#     "sf_sis_4_T1"
#   ),
#   q5_t1 = c(
#     "sf_sis_5_T1"
#   ),
#   q6_t1 = c(
#     "sf_sis_6_T1"
#   ),
#   q7_t1 = c(
#     "sf_sis_7_T1"
#   ),
#   q8_t1 = c(
#     "sf_sis_8_T1"
#   ), 
#   sf_sis_total_t1 = c(
#     "sf_sis_1_T1",
#     "sf_sis_2_T1",
#     "sf_sis_3_T1",
#     "sf_sis_4_T1",
#     "sf_sis_5_T1",
#     "sf_sis_6_T1",
#     "sf_sis_7_T1",
#     "sf_sis_8_T1"
#   ),
#   q1_t2 = c(
#     "sf_sis_1_T2"
#   ),
#   q2_t2 = c(
#     "sf_sis_2_T2"
#   ),
#   q3_t2 = c(
#     "sf_sis_3_T2"
#   ),
#   q4_t2 = c(
#     "sf_sis_4_T2"
#   ),
#   q5_t2 = c(
#     "sf_sis_5_T2"
#   ),
#   q6_t2 = c(
#     "sf_sis_6_T2"
#   ),
#   q7_t2 = c(
#     "sf_sis_7_T2"
#   ),
#   q8_t2 = c(
#     "sf_sis_8_T2"
#   ), 
#   sf_sis_total_t2 = c(
#     "sf_sis_1_T2",
#     "sf_sis_2_T2",
#     "sf_sis_3_T2",
#     "sf_sis_4_T2",
#     "sf_sis_5_T2",
#     "sf_sis_6_T2",
#     "sf_sis_7_T2",
#     "sf_sis_8_T2"
#   ),
#   q1_t3 = c(
#     "sf_sis_1_T3"
#   ),
#   q2_t3 = c(
#     "sf_sis_2_T3"
#   ),
#   q3_t3 = c(
#     "sf_sis_3_T3"
#   ),
#   q4_t3 = c(
#     "sf_sis_4_T3"
#   ),
#   q5_t3 = c(
#     "sf_sis_5_T3"
#   ),
#   q6_t3 = c(
#     "sf_sis_6_T3"
#   ),
#   q7_t3 = c(
#     "sf_sis_7_T3"
#   ),
#   q8_t3 = c(
#     "sf_sis_8_T3"
#   ), 
#   sf_sis_total_t3 = c(
#     "sf_sis_1_T3",
#     "sf_sis_2_T3",
#     "sf_sis_3_T3",
#     "sf_sis_4_T3",
#     "sf_sis_5_T3",
#     "sf_sis_6_T3",
#     "sf_sis_7_T3",
#     "sf_sis_8_T3"
#   )
# )
# 
# sf_sis.scale.sum <- scoreItems(keys = sf_sis_a.keys, items = headsup_group_a, totals = TRUE)
# sf_sis.scale.sum
# sf_sis.sum.scores <- sf_sis.scale.sum$scores # the actual scores are saved in the scores object
# sf_sis.sum.scores
# 
# # raw scores
# headTail(round(sf_sis.sum.scores, 2))
# 
# # describe
# sf_sis.sum.tbl <- psych::describe(sf_sis.sum.scores)
# kable(sf_sis.sum.tbl)

```

# BAI Score 
```{r bai}
# character to numeric for total scores
headsup_group_a$bai_total_T3 <- as.numeric(headsup_group_a$bai_total_T3)
headsup_group_b$bai_total_T3 <- as.numeric(headsup_group_b$bai_total_T3)

# grp a
headsup_group_a %>%
  get_summary_stats(bai_total_T0, bai_total_T1, bai_total_T2, bai_total_T3) %>%
  dplyr::mutate(across(where(is.numeric), round, 2))

# grp b
headsup_group_b %>%
  get_summary_stats(bai_total_T0, bai_total_T1, bai_total_T2, bai_total_T3) %>%
  dplyr::mutate(across(where(is.numeric), round, 2))

```

# BDI Score
```{r bdi}
# character to numeric for total scores
headsup_group_a$bdi_total_T3 <- as.numeric(headsup_group_a$bdi_total_T3)
headsup_group_b$bdi_total_T3 <- as.numeric(headsup_group_b$bdi_total_T3)

# grp a
headsup_group_a %>%
  get_summary_stats(bdi_total_T0, bdi_total_T1, bdi_total_T2, bdi_total_T3) %>%
  dplyr::mutate(across(where(is.numeric), round, 2))

# grp b
headsup_group_b %>%
  get_summary_stats(bdi_total_T0, bdi_total_T1, bdi_total_T2, bdi_total_T3) %>%
  dplyr::mutate(across(where(is.numeric), round, 2))

```

# DASS Score
```{r dass}
# character to numeric for total scores
headsup_group_a$dass_total_score_T2 <- as.numeric(headsup_group_a$dass_total_score_T2)
headsup_group_b$dass_total_score_T2 <- as.numeric(headsup_group_b$dass_total_score_T2)
headsup_group_a$dass_total_score_T3 <- as.numeric(headsup_group_a$dass_total_score_T3)
headsup_group_b$dass_total_score_T3 <- as.numeric(headsup_group_b$dass_total_score_T3)
headsup_group_a$dass_anx_score_T2 <- as.numeric(headsup_group_a$dass_anx_score_T2)
headsup_group_b$dass_anx_score_T2 <- as.numeric(headsup_group_b$dass_anx_score_T2)
headsup_group_a$dass_anx_score_T3 <- as.numeric(headsup_group_a$dass_anx_score_T3)
headsup_group_b$dass_anx_score_T3 <- as.numeric(headsup_group_b$dass_anx_score_T3)
headsup_group_a$dass_dep_score_T2 <- as.numeric(headsup_group_a$dass_dep_score_T2)
headsup_group_b$dass_dep_score_T2 <- as.numeric(headsup_group_b$dass_dep_score_T2)
headsup_group_a$dass_dep_score_T3 <- as.numeric(headsup_group_a$dass_dep_score_T3)
headsup_group_b$dass_dep_score_T3 <- as.numeric(headsup_group_b$dass_dep_score_T3)
headsup_group_a$dass_stress_score_T2 <- as.numeric(headsup_group_a$dass_stress_score_T2)
headsup_group_b$dass_stress_score_T2 <- as.numeric(headsup_group_b$dass_stress_score_T2)
headsup_group_a$dass_stress_score_T3 <- as.numeric(headsup_group_a$dass_stress_score_T3)
headsup_group_b$dass_stress_score_T3 <- as.numeric(headsup_group_b$dass_stress_score_T3)

# grp a totals
headsup_group_a %>%
  get_summary_stats(dass_total_score_T0, dass_total_score_T1, dass_total_score_T2, dass_total_score_T3) %>%
  dplyr::mutate(across(where(is.numeric), round, 2))

# grp b totals
headsup_group_b %>%
  get_summary_stats(dass_total_score_T0, dass_total_score_T1, dass_total_score_T2, dass_total_score_T3) %>%
  dplyr::mutate(across(where(is.numeric), round, 2))

# grp a dass-a, dass-d, dass-s
headsup_group_a %>%
  get_summary_stats(dass_anx_score_T0, dass_anx_score_T1, dass_anx_score_T2, dass_anx_score_T3) %>%
  dplyr::mutate(across(where(is.numeric), round, 2))

headsup_group_a %>%
  get_summary_stats(dass_dep_score_T0, dass_dep_score_T1, dass_dep_score_T2, dass_dep_score_T3) %>%
  dplyr::mutate(across(where(is.numeric), round, 2))

headsup_group_a %>%
  get_summary_stats(dass_stress_score_T0, dass_stress_score_T1, dass_stress_score_T2, dass_stress_score_T3) %>%
  dplyr::mutate(across(where(is.numeric), round, 2))

# grp b dass-a, dass-d, dass-s
headsup_group_a %>%
  get_summary_stats(dass_anx_score_T0, dass_anx_score_T1, dass_anx_score_T2, dass_anx_score_T3) %>%
  dplyr::mutate(across(where(is.numeric), round, 2))

headsup_group_a %>%
  get_summary_stats(dass_dep_score_T0, dass_dep_score_T1, dass_dep_score_T2, dass_dep_score_T3) %>%
  dplyr::mutate(across(where(is.numeric), round, 2))

headsup_group_b %>%
  get_summary_stats(dass_stress_score_T0, dass_stress_score_T1, dass_stress_score_T2, dass_stress_score_T3) %>%
  dplyr::mutate(across(where(is.numeric), round, 2))

```

# SIS Score
```{r sis}
# # grp a
# # sis1 strength
# # sis2 memory
# # sis3 emotion
# # sis4 communication
# # sis5 adl
# # sis6 mobility
# # sis7 hand function
# # sis8 social participation
headsup_group_a %>%
  get_summary_stats(sf_sis_1_T0, sf_sis_2_T0, sf_sis_3_T0, sf_sis_4_T0, sf_sis_5_T0, sf_sis_6_T0, sf_sis_7_T0, sf_sis_8_T0)
# 
headsup_group_a %>%
  get_summary_stats(sf_sis_1_T1, sf_sis_2_T1, sf_sis_3_T1, sf_sis_4_T1, sf_sis_5_T1, sf_sis_6_T1, sf_sis_7_T1, sf_sis_8_T1)
# 
headsup_group_a$sf_sis_1_T2 <- as.numeric(headsup_group_a$sf_sis_1_T2)
headsup_group_b$sf_sis_1_T2 <- as.numeric(headsup_group_b$sf_sis_1_T2)
headsup_group_a$sf_sis_2_T2 <- as.numeric(headsup_group_a$sf_sis_2_T2)
headsup_group_b$sf_sis_2_T2 <- as.numeric(headsup_group_b$sf_sis_2_T2)
headsup_group_a$sf_sis_3_T2 <- as.numeric(headsup_group_a$sf_sis_3_T2)
headsup_group_b$sf_sis_3_T2 <- as.numeric(headsup_group_b$sf_sis_3_T2)
headsup_group_a$sf_sis_4_T2 <- as.numeric(headsup_group_a$sf_sis_4_T2)
headsup_group_b$sf_sis_4_T2 <- as.numeric(headsup_group_b$sf_sis_4_T2)
headsup_group_a$sf_sis_5_T2 <- as.numeric(headsup_group_a$sf_sis_5_T2)
headsup_group_b$sf_sis_5_T2 <- as.numeric(headsup_group_b$sf_sis_5_T2)
headsup_group_a$sf_sis_6_T2 <- as.numeric(headsup_group_a$sf_sis_6_T2)
headsup_group_b$sf_sis_6_T2 <- as.numeric(headsup_group_b$sf_sis_6_T2)
headsup_group_a$sf_sis_7_T2 <- as.numeric(headsup_group_a$sf_sis_7_T2)
headsup_group_b$sf_sis_7_T2 <- as.numeric(headsup_group_b$sf_sis_7_T2)
headsup_group_a$sf_sis_8_T2 <- as.numeric(headsup_group_a$sf_sis_8_T2)
headsup_group_b$sf_sis_8_T2 <- as.numeric(headsup_group_b$sf_sis_8_T2)
#
headsup_group_a$sf_sis_1_T3 <- as.numeric(headsup_group_a$sf_sis_1_T3)
headsup_group_b$sf_sis_1_T3 <- as.numeric(headsup_group_b$sf_sis_1_T3)
headsup_group_a$sf_sis_2_T3 <- as.numeric(headsup_group_a$sf_sis_2_T3)
headsup_group_b$sf_sis_2_T3 <- as.numeric(headsup_group_b$sf_sis_2_T3)
headsup_group_a$sf_sis_3_T3 <- as.numeric(headsup_group_a$sf_sis_3_T3)
headsup_group_b$sf_sis_3_T3 <- as.numeric(headsup_group_b$sf_sis_3_T3)
headsup_group_a$sf_sis_4_T3 <- as.numeric(headsup_group_a$sf_sis_4_T3)
headsup_group_b$sf_sis_4_T3 <- as.numeric(headsup_group_b$sf_sis_4_T3)
headsup_group_a$sf_sis_5_T3 <- as.numeric(headsup_group_a$sf_sis_5_T3)
headsup_group_b$sf_sis_5_T3 <- as.numeric(headsup_group_b$sf_sis_5_T3)
headsup_group_a$sf_sis_6_T3 <- as.numeric(headsup_group_a$sf_sis_6_T3)
headsup_group_b$sf_sis_6_T3 <- as.numeric(headsup_group_b$sf_sis_6_T3)
headsup_group_a$sf_sis_7_T3 <- as.numeric(headsup_group_a$sf_sis_7_T3)
headsup_group_b$sf_sis_7_T3 <- as.numeric(headsup_group_b$sf_sis_7_T3)
headsup_group_a$sf_sis_8_T3 <- as.numeric(headsup_group_a$sf_sis_8_T3)
headsup_group_b$sf_sis_8_T3 <- as.numeric(headsup_group_b$sf_sis_8_T3)

headsup_group_a %>%
  get_summary_stats(sf_sis_1_T2, sf_sis_2_T2, sf_sis_3_T2, sf_sis_4_T2, sf_sis_5_T2, sf_sis_6_T2, sf_sis_7_T2, sf_sis_8_T2)

headsup_group_b %>%
  get_summary_stats(sf_sis_1_T2, sf_sis_2_T2, sf_sis_3_T2, sf_sis_4_T2, sf_sis_5_T2, sf_sis_6_T2, sf_sis_7_T2, sf_sis_8_T2)
#
headsup_group_a %>%
  get_summary_stats(sf_sis_1_T3, sf_sis_2_T3, sf_sis_3_T3, sf_sis_4_T3, sf_sis_5_T3, sf_sis_6_T3, sf_sis_7_T3, sf_sis_8_T3)
#
headsup_group_b %>%
  get_summary_stats(sf_sis_1_T3, sf_sis_2_T3, sf_sis_3_T3, sf_sis_4_T3, sf_sis_5_T3, sf_sis_6_T3, sf_sis_7_T3, sf_sis_8_T3)
# 
# #
# headsup_group_a %>%
#   tabyl(sf_sis_feedback_3_T1) %>%
#   adorn_pct_formatting()
# 
# headsup_group_b %>%
#   tabyl(sf_sis_feedback_3_T1) %>%
#   adorn_pct_formatting()
# #
# headsup_group_a %>%
#   tabyl(sf_sis_feedback_3a_T1) %>%
#   adorn_pct_formatting()
# 
# headsup_group_b %>%
#   tabyl(sf_sis_feedback_3a_T1) %>%
#   adorn_pct_formatting()
# 
# 
# effect sizes
interpret_cohens_d(
cohens_d(headsup_group_b$bai_total_T0, headsup_group_b$bai_total_T1))

interpret_cohens_d(
cohens_d(headsup_group_b$bai_total_T1, headsup_group_b$bai_total_T2))

interpret_cohens_d(
cohens_d(headsup_group_b$bai_total_T0, headsup_group_b$bai_total_T2))

interpret_cohens_d(
cohens_d(headsup_group_b$sf_sis_8_T0, headsup_group_b$sf_sis_8_T1))

interpret_cohens_d(
cohens_d(headsup_group_a$sf_sis_8_T0, headsup_group_a$sf_sis_8_T2))

interpret_cohens_d(
cohens_d(headsup_group_b$sf_sis_8_T0, headsup_group_b$sf_sis_8_T2))

unique(headsup_group_a$sf_sis_1_T2)
class(headsup_group_a$sf_sis_1_T2)

interpret_cohens_d(
cohens_d(headsup_group_a$sf_sis_2_T1, headsup_group_a$sf_sis_2_T2))

# mean change scores

mean(headsup_group_b$sf_sis_8_T0, na.rm = T) -
mean(headsup_group_b$sf_sis_8_T1, na.rm = T)
#
interpret_cohens_d(
cohens_d(
  headsup_group_b$sf_sis_8_T0,
  headsup_group_b$sf_sis_8_T1))
#


#
mean(headsup_group_b$sf_sis_8_T1, na.rm = T) -
mean(headsup_group_b$sf_sis_8_T2, na.rm = T)

interpret_cohens_d(
cohens_d(headsup_group_b$sf_sis_8_T1, headsup_group_b$sf_sis_8_T2))

mean(headsup_group_b$sf_sis_8_T0, na.rm = T) -
mean(headsup_group_b$sf_sis_8_T2, na.rm = T)

class(headsup_group_a$dass_anx_score_T2)
headsup_group_b$dass_total_score_T2 <- as.numeric(headsup_group_b$dass_total_score_T2)

mean(headsup_group_b$dass_total_score_T0, na.rm = T) -
mean(headsup_group_b$dass_total_score_T2, na.rm = T)

mean(headsup_group_a$sf_sis_8_T0, na.rm = T) -
mean(headsup_group_a$sf_sis_8_T2, na.rm = T)

```

# Loss to follow up
```{r loss}
# headsup_t0_t1_t2_t3 %>%
#   group_by(p_id) %>%
#     summarize(censored = max(batch) < 1)

headsup_t0_t1_t2_t3 %>%
  tabyl(bai_1_T1)

# bdi
headsup_group_b %>%
  tabyl(bdi_1_T1) %>%
  adorn_totals()
# bd1 t0 = 62
# bdi t1 = 13 lost
# bdi t2 = 11 lost
# bdi t3 = 15 lost

# bai
headsup_t0_t1_t2_t3 %>%
  tabyl(bai_1_T3) %>%
  adorn_totals()
# bai t0 = 61
# bai t1 = 13 lost
# bai t2 = 12 lost
# bai t3 = 15 lost

# dass
headsup_t0_t1_t2_t3 %>%
  tabyl(dass_21_1_s_T3) %>%
  adorn_totals()
# dass t0 = 62
# dass t1 = 12 lost
# dass t2 = 12 lost
# dass t3 = 16 lost

# sf sis
headsup_t0_t1_t2_t3 %>%
  tabyl(sf_sis_1_T3) %>%
  adorn_totals()
# sfsis t0 = 62
# sfsis t1 = 12 lost
# sfsis t2 = 12 lost
# sfsis t3 = 18 lost

# ruq
headsup_t0_t1_t2_t3 %>%
  tabyl(ruq_1_a_T3) %>%
  adorn_totals()
# ruq t0 = 62
# ruq t1 = 13 lost
# ruq t2 = 12 lost
# ruq t3 = 17 lost

# ruq
headsup_t0_t1_t2_t3 %>%
  tabyl(ruq_1_a_T3) %>%
  adorn_totals()
# ruq t0 = 62
# ruq t1 = 13 lost
# ruq t2 = 12 lost
# ruq t3 = 17 lost

```


# CONSORT Population
```{r consort}

#install.packages("PRISMAstatement")
#library(PRISMAstatement)

# flow_exclusions(
#   incl_counts = c(972, 132, 77, 14),
#   total_label = "Total Screened",
#   incl_labels = c("Consented", "Completed Study", "BMI <= 30"),
#   excl_labels = c("Declined Consent", "Failed to Complete", "BMI > 30")
# )

```

